# Generated by Django 5.2.1 on 2025-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField()),
                ('about_company', models.TextField()),
                ('product_and_services', models.TextField()),
                ('greeting_message', models.TextField()),
                ('thanks_message', models.TextField()),
            ],
        ),
    ]
