# Generated by Django 5.2.1 on 2025-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='epoch',
            field=models.IntegerField(default=1000),
        ),
    ]
