# Generated by Django 5.2.1 on 2025-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyinformation_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='epoch',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
